# permissions for end users to view packages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-viewer-role
rules:
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packages/status
  verbs:
  - get
