# permissions for end users to view packagecontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagecontroller-viewer-role
rules:
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagecontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagecontrollers/status
  verbs:
  - get
