# permissions for end users to view packagebundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagebundle-viewer-role
rules:
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagebundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagebundles/status
  verbs:
  - get
