# permissions for end users to view packagebundlecontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagebundlecontroller-viewer-role
rules:
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagebundlecontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagebundlecontrollers/status
  verbs:
  - get
