# permissions for end users to edit packagecontrollercs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagecontroller-editor-role
rules:
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagecontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - packages.eks.amazonaws.com
  resources:
  - packagecontrollers/status
  verbs:
  - get
